// =============================================================================
// firebase_options_placeholder.dart
// =============================================================================
//
// ⚠️  THIS IS A PLACEHOLDER FILE — DO NOT USE IN PRODUCTION
//
// This file demonstrates the structure of the auto-generated
// `firebase_options.dart` file. The real file is created by the FlutterFire CLI
// and contains your actual Firebase project credentials.
//
// =============================================================================
//
// HOW TO GENERATE THE REAL firebase_options.dart
// -----------------------------------------------
//
// 1. Install the FlutterFire CLI globally:
//
//      dart pub global activate flutterfire_cli
//
// 2. Make sure you have the Firebase CLI installed and are logged in:
//
//      npm install -g firebase-tools
//      firebase login
//
// 3. Navigate to your Flutter project root (e.g., packages/parent_app/ or
//    packages/child_app/) and run:
//
//      flutterfire configure
//
//    This will:
//      - Prompt you to select your Firebase project (or create a new one)
//      - Ask which platforms to configure (Android, iOS, Web, macOS)
//      - Automatically register your app with Firebase
//      - Generate lib/firebase_options.dart with your real credentials
//
// 4. The generated file will contain a class like `DefaultFirebaseOptions`
//    with platform-specific configurations. Use it in your main.dart:
//
//      import 'firebase_options.dart';
//
//      void main() async {
//        WidgetsFlutterBinding.ensureInitialized();
//        await Firebase.initializeApp(
//          options: DefaultFirebaseOptions.currentPlatform,
//        );
//        runApp(const MyApp());
//      }
//
// 5. IMPORTANT: Add firebase_options.dart to your .gitignore if your
//    repository is public, as it contains sensitive API keys:
//
//      # Firebase
//      lib/firebase_options.dart
//
// 6. For CI/CD pipelines, store Firebase configuration as environment
//    variables or encrypted secrets and generate the file at build time.
//
// =============================================================================
//
// SEPARATE FIREBASE APPS FOR PARENT & CHILD
// ------------------------------------------
//
// StudyGuardian AI uses two separate Flutter apps (parent_app and child_app).
// Both apps connect to the SAME Firebase project but are registered as
// separate Android apps with different package names:
//
//   - Parent App: com.studyguardian.parent
//   - Child App:  com.studyguardian.child
//
// Run `flutterfire configure` in EACH app's directory to generate its own
// firebase_options.dart with the correct app-specific configuration.
//
// =============================================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Placeholder Firebase configuration options.
///
/// Replace this class with the auto-generated `DefaultFirebaseOptions` class
/// by running `flutterfire configure` in your project root.
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows. '
          'Run `flutterfire configure` to generate platform-specific config.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux. '
          'Run `flutterfire configure` to generate platform-specific config.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ---------------------------------------------------------------------------
  // ⚠️  PLACEHOLDER VALUES BELOW — Replace with real values from FlutterFire CLI
  // ---------------------------------------------------------------------------

  /// Android Firebase configuration.
  ///
  /// Generated by `flutterfire configure` for your Android app.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR-ANDROID-API-KEY',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-firebase-project-id',
    storageBucket: 'your-firebase-project-id.appspot.com',
  );

  /// iOS Firebase configuration.
  ///
  /// Generated by `flutterfire configure` for your iOS app.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-IOS-API-KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-firebase-project-id',
    storageBucket: 'your-firebase-project-id.appspot.com',
    iosBundleId: 'com.studyguardian.parent', // or com.studyguardian.child
  );

  /// Web Firebase configuration.
  ///
  /// Generated by `flutterfire configure` for your Web app.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-WEB-API-KEY',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-firebase-project-id',
    authDomain: 'your-firebase-project-id.firebaseapp.com',
    storageBucket: 'your-firebase-project-id.appspot.com',
  );

  /// macOS Firebase configuration.
  ///
  /// Generated by `flutterfire configure` for your macOS app.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-MACOS-API-KEY',
    appId: '1:000000000000:macos:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-firebase-project-id',
    storageBucket: 'your-firebase-project-id.appspot.com',
    iosBundleId: 'com.studyguardian.parent', // or com.studyguardian.child
  );
}
