import 'package:cloud_firestore/cloud_firestore.dart';

/// Types of notifications generated by the StudyGuardian AI system.
enum NotificationType {
  batteryLow,
  batteryFull,
  deviceOffline,
  deviceOnline,
  newAppInstalled,
  studyGoalAchieved,
  dailyReportReady,
  tabletRestarted,
  appRemoved;

  /// Human-readable display name for this notification type.
  String get displayName {
    switch (this) {
      case NotificationType.batteryLow:
        return 'Battery Low';
      case NotificationType.batteryFull:
        return 'Battery Full';
      case NotificationType.deviceOffline:
        return 'Device Offline';
      case NotificationType.deviceOnline:
        return 'Device Online';
      case NotificationType.newAppInstalled:
        return 'New App Installed';
      case NotificationType.studyGoalAchieved:
        return 'Study Goal Achieved';
      case NotificationType.dailyReportReady:
        return 'Daily Report Ready';
      case NotificationType.tabletRestarted:
        return 'Tablet Restarted';
      case NotificationType.appRemoved:
        return 'App Removed';
    }
  }

  /// Parses a [String] value into a [NotificationType].
  ///
  /// Returns [NotificationType.deviceOnline] if the value does not match.
  static NotificationType fromString(String? value) {
    if (value == null || value.isEmpty) return NotificationType.deviceOnline;
    return NotificationType.values.firstWhere(
      (type) => type.name == value,
      orElse: () => NotificationType.deviceOnline,
    );
  }
}

/// Represents a notification sent to a family group.
///
/// Notifications are generated by the system when notable events occur
/// on monitored devices (e.g., low battery, new app installed, daily
/// report availability).
class NotificationModel {
  /// Unique identifier for this notification.
  final String id;

  /// The ID of the family group this notification belongs to.
  final String familyId;

  /// The type of notification event.
  final NotificationType type;

  /// Title text displayed in the notification.
  final String title;

  /// Body text with details about the notification event.
  final String body;

  /// The ID of the device that triggered this notification.
  final String deviceId;

  /// The display name of the device that triggered this notification.
  final String deviceName;

  /// Timestamp when this notification was created.
  final DateTime timestamp;

  /// Whether this notification has been read by the user.
  final bool read;

  const NotificationModel({
    required this.id,
    required this.familyId,
    required this.type,
    required this.title,
    required this.body,
    required this.deviceId,
    required this.deviceName,
    required this.timestamp,
    this.read = false,
  });

  /// Whether this notification is unread.
  bool get isUnread => !read;

  /// Creates a [NotificationModel] from a Firestore [DocumentSnapshot].
  factory NotificationModel.fromFirestore(
      DocumentSnapshot<Map<String, dynamic>> doc) {
    final data = doc.data() ?? {};
    return NotificationModel(
      id: doc.id,
      familyId: data['familyId'] as String? ?? '',
      type: NotificationType.fromString(data['type'] as String?),
      title: data['title'] as String? ?? '',
      body: data['body'] as String? ?? '',
      deviceId: data['deviceId'] as String? ?? '',
      deviceName: data['deviceName'] as String? ?? '',
      timestamp:
          (data['timestamp'] as Timestamp?)?.toDate() ?? DateTime.now(),
      read: data['read'] as bool? ?? false,
    );
  }

  /// Converts this model to a Firestore-compatible map.
  Map<String, dynamic> toFirestore() {
    return {
      'familyId': familyId,
      'type': type.name,
      'title': title,
      'body': body,
      'deviceId': deviceId,
      'deviceName': deviceName,
      'timestamp': Timestamp.fromDate(timestamp),
      'read': read,
    };
  }

  /// Creates a [NotificationModel] from a plain JSON map.
  factory NotificationModel.fromJson(Map<String, dynamic> json) {
    return NotificationModel(
      id: json['id'] as String? ?? '',
      familyId: json['familyId'] as String? ?? '',
      type: NotificationType.fromString(json['type'] as String?),
      title: json['title'] as String? ?? '',
      body: json['body'] as String? ?? '',
      deviceId: json['deviceId'] as String? ?? '',
      deviceName: json['deviceName'] as String? ?? '',
      timestamp: json['timestamp'] != null
          ? DateTime.parse(json['timestamp'] as String)
          : DateTime.now(),
      read: json['read'] as bool? ?? false,
    );
  }

  /// Converts this model to a plain JSON map.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'familyId': familyId,
      'type': type.name,
      'title': title,
      'body': body,
      'deviceId': deviceId,
      'deviceName': deviceName,
      'timestamp': timestamp.toIso8601String(),
      'read': read,
    };
  }

  /// Creates a copy of this model with the given fields replaced.
  NotificationModel copyWith({
    String? id,
    String? familyId,
    NotificationType? type,
    String? title,
    String? body,
    String? deviceId,
    String? deviceName,
    DateTime? timestamp,
    bool? read,
  }) {
    return NotificationModel(
      id: id ?? this.id,
      familyId: familyId ?? this.familyId,
      type: type ?? this.type,
      title: title ?? this.title,
      body: body ?? this.body,
      deviceId: deviceId ?? this.deviceId,
      deviceName: deviceName ?? this.deviceName,
      timestamp: timestamp ?? this.timestamp,
      read: read ?? this.read,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationModel &&
          runtimeType == other.runtimeType &&
          id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() =>
      'NotificationModel(id: $id, type: ${type.displayName}, '
      'title: $title, read: $read)';
}
